### ISSUE TITLE
Fail to import data from Scrapbook

### ISSUE THREAD

**Issue by amitbha** [GChristensen/scrapyard#1]
OS: ArchLinux
Firefox 70.0
Scrapyard 0.3.5

![2019-10-29-145847_1440x900_scrot](https://user-images.githubusercontent.com/4060625/67744598-f40def80-fa5c-11e9-97eb-02a63bb65fcb.png)

![1029-1504](https://user-images.githubusercontent.com/4060625/67744967-f45aba80-fa5d-11e9-82c4-38a9b7d0ae5a.jpg)

**Comment by GChristensen** [comment]
It seems, that same-origin [mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) of the fetch API does not work on Linux. 
As a workaround, in Scrapyard 0.3.6 it is possible to import RDF files exposed over HTTP.
For example, if you put ScrapBook folder in the htdocs folder of [lighttpd](https://www.lighttpd.net/),  you would be able to import it with the http://localhost/ScrapBook/scrapbook.rdf path.
