### ISSUE TITLE
Request: Open Scrapyard sidebar per keyboard shortcut

### ISSUE THREAD

**Issue by Lyzair** [GChristensen/scrapyard#10]
Hey there.
Bookmarks and history can be opened with Ctrl+B/H.
Is it possible to add a shortcut for the Scrapyard sidebar?

Thanks in advance.

**Comment by GChristensen** [comment]
It should be theoretically possible with the most recent Firefox (but I'm not sure for 100%). Currently, I can't proceed with the development, so this issue will be open for some time.

**Comment by GChristensen** [comment]
Added Alt+Y keyboard shortcut. Could be customized in Firefox options: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox (as for any addon).
