### ISSUE TITLE
Database gone

### ISSUE THREAD

**Issue by tulipuser** [GChristensen/scrapyard#12]
It is now the 2nd time that all of my stored Webpages inside the scrapyard database are gone.
:-(
Anything left are the Firefox Bookmarks.

Where is teh Database stored?
Can I reread that Database data?
I did not use cloud or export.

**Comment by GChristensen** [comment]
There is a high probability that everything is still there, but some node was created at the top level of the jsTree without the reference to the invisible root node by some unforeseen way.
You can browse DB contents in [storage inspector](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector), if you open it (F12), for example at the Scrapyard settings page.
The better way to figure out what is happening is to read the debug console at about:debugging page (you need to click "This Firefox" and inspect the Scrapyard addon there).
But if you figure what has happened, the restoration may require some advanced JavaScript trickery, and unfortunately it may be easier to scrap entire addon installation (remove and reinstall it).
Please post debug messages if you will see the console to prevent this from happening in the future.

**Comment by tulipuser** [comment]
Now I deleted the Addon and reinstalled it.
Now I connot Archive anything and cannot create a folder under default.

**Comment by GChristensen** [comment]
Yes, this definitely that bug. It seems, that it is necessary to restart Firefox between deletion and new installation. In the future releases, I'll try to mitigate it by forcefully checking the parent node of the top-level object. You may archive your current profile to see if that will work.

**Comment by tulipuser** [comment]
Now I found out: If i switch off "Show Firefox bookmarks shelf"
It is not possible to Archive a Website

**Comment by tulipuser** [comment]
So. Today the Database was gone again. Everything deleted. I did not do any scrapyard update.

**Comment by GChristensen** [comment]
Well, this is pretty curious. I added a bug fix in previous versions to mitigate this error. If you disabled automatic updates maybe you need to enable them. 

If you haven't removed the addon yet, you may check is your data is still there by the following way:
1. Open Scrapyard settings page.
2. Press F12 (open debug console)
3. Open "Storage" tab.

The saved items should be available under: IndexedDB -> <moz-extension:...> -> scrapyard -> nodes

**Comment by tulipuser** [comment]
automatic update is set to Standard, Version is 0.4.8.

"The saved items should be available under: IndexedDB -> moz-extension:... -> scrapyard -> nodes"
Here I only see the Firefox Bookmarks and no saved scrapyard items.

**Comment by GChristensen** [comment]
The recent version is 0.4.9 of May 11. Probably you need to force updates through the corresponding item under the cog menu.

**Comment by tulipuser** [comment]
And everything is gone again. I cannot believe it. I think I must look out for another scrapbook. :-/

**Comment by tulipuser** [comment]
And the dropbox integration is not working ether. "Error accessing cloud"

**Comment by tulipuser** [comment]
Database gone again :-/
