### ISSUE TITLE
Limited storage

### ISSUE THREAD

**Issue by cyrant** [GChristensen/scrapyard#13]
Default storage is limited to 2GB in Firefox. Please use persistent storage instead.

**Comment by GChristensen** [comment]
IndexedDB is used.

**Comment by cyrant** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509443

**Comment by GChristensen** [comment]
Thanks for the link. navigator.storage.persisted() returns ture, so the persistent storage is used by default.
