### ISSUE TITLE
Tags show up in Scrapyard but not in FF bookmark manager

### ISSUE THREAD

**Issue by patoski** [GChristensen/scrapyard#15]
Thank you so much for creating Scrapyard. It has changed the quality of my life! I'm no longer stressed out about losing information, having tons of tabs open, or worried that a site with great information will no longer become available. Thank you!!

Whenever I create a new bookmark and add a tag in Scrapyard, it doesn't show up in the Firefox bookmark manager. I see the same behavior whenever adding a tag to an existing bookmark as well.

**Comment by GChristensen** [comment]
As far as I know, there is currently no api for bookmark tags in Firefox WebExtension API.
