### ISSUE TITLE
Automatic backup to cloud

### ISSUE THREAD

**Issue by patoski** [GChristensen/scrapyard#16]
It would be great if the import/export functionality could be automated. Also, it would be even better if we could backup to cloud.

**Comment by GChristensen** [comment]
Import/Export is intended primarily for the migration of existing bookmarks. I recommend to use third-party software to periodically back up your entire firefox profile. Although it is possible to backup automatically to the cloud, this may take a while for users with a great amount of bookmarks and will require quite advanced logic to implement on a Dropbox backend, so there probably will be no such feature, until the dedicated cloud backend will be created.
