### ISSUE TITLE
Write-Protection

### ISSUE THREAD

**Issue by Pyradur** [GChristensen/scrapyard#2]
It seems that during installation anywhere is a write-protection on work, because I neither got any default shelfs nor could I create one. After creating there was no new shelf. And within the options there is no one item activated.

**Comment by GChristensen** [comment]
Can't say anything without Firefox/OS version and log output.

**Comment by Pyradur** [comment]
Re: [GChristensen/scrapyard] Write-Protection (#2)



After "cleaning up" Firefox an reinstalling Scrapyard it looks all good.

--
Viele Grüße

Reinhold Riedersberger




Can't say anything without Firefox/OS version and log output.
