### ISSUE TITLE
Feature request:  Add 2 popular cloud storage providers

### ISSUE THREAD

**Issue by timlt** [GChristensen/scrapyard#20]
Would it be possible to add cloud storage providers Google Drive and Onedrive?

With these and Dropbox, you'd have probably 90% of users covered for their existing cloud storage provider.

**Comment by GChristensen** [comment]
It is theoretically possible, but unfortunately, Mozilla requires a source of any library you use in your project. Since the libraries from Microsoft and Google are obfuscated, there is no way to use them in the public distributions of Scrapyard.
