### ISSUE TITLE
Search in content still doesn't work. 

### ISSUE THREAD

**Issue by timlt** [GChristensen/scrapyard#21]
Tested the fix, still not working on my machines anyway (all FF 78+, Win10 x64 Pro).  

To repro:
1. Archive a page.
2. Set the Scrapyard search context to "content", and "Everything". 
3. Search for a term in that page.  

Result:  Nothing returned.
Note:  Search works for titles, and tags.  Also, if this is possible, would be nice to show an excerpt of returned text with the search term highlighted for each individual search hit.  I noticed another scrapbook add-on (Scrapbee??) does something like that.

**Comment by GChristensen** [comment]
Can not reproduce, it works in my environment. Content search is limited to the currently active shelf (everything shelf searches everywhere). Please check that addon is updated to the recent version (0.4.11).

> Also, if this is possible, would be nice to show an excerpt of returned text with the search term highlighted for each individual search hit. I noticed another scrapbook add-on (Scrapbee??) 

It searches through all files, Scrapyard uses indexes and there is no place in the tree component to display the context.
