### ISSUE TITLE
Error archiving page

### ISSUE THREAD

**Issue by desiregn** [GChristensen/scrapyard#22]
I've lost all my pages and ability to save new. Reinstall of the extension wont help. In Scrapyard's sidebar appeared infinity load
 
![image](https://user-images.githubusercontent.com/13287052/89098964-1d0d4780-d416-11ea-9024-ebea9677e1f9.png)

**Comment by GChristensen** [comment]
It seems that this is a tree-view or some startup issue. If you have not uninstalled addon before reinstall, there are the chances that all your pages are still there. At first, we need to understand what is wrong. The only way to accomplish this is to get some debug information. You need to:

-  Close Scraypard sidebar if it is opened
-  Close Firefox
-  Start it again
-  Open a new tab and enter the following URL: **about:debugging**
-  At this page click "This Firefox" at the top left
-  Find the Scrapyard addon and click "Inspect"
-  On the opened page click the "Console" tab at the top row
-  Open Scrapyard sidebar
-  Post the contents of the console here.

**Comment by desiregn** [comment]
```js
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
SyntaxError: invalid identity escape in regular expression proto.js:1:9
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: jar:file:///usr/lib/firefox-esr/browser/features/webcompat@mozilla.org.xpi!/experiment-apis/pictureInPicture.js :: getPolicies :: line 70"  data: no] pictureInPicture.js:70:11
Error: An unexpected error occurred undefined:14:57
Error: Incorrect argument types for pictureInPictureParent.setOverrides. picture_in_picture_overrides.js:15:36
==> background.js loaded background.js:313:9
==> savepage/background.js loaded background.js:1227:9
Error: Could not establish connection. Receiving end does not exist. backend.js:1560:33
Content Security Policy: Couldn’t process unknown directive ‘navigation-to’
SyntaxError: invalid identity escape in regular expression proto.js:1:9
==> sidebar.js loaded sidebar.js:713:9
TypeError: document.title.translate is not a function
sidebar.js:293:37
```

**Comment by GChristensen** [comment]
What version of Firefox you are using?

**Comment by desiregn** [comment]
68.7.0 (esr)
Now I disable uBlock extension and change privacy settings from custom strict to standard: doesn't help

**Comment by GChristensen** [comment]
The recent version of the add-on uses the features that are available only in recent versions of Firefox. I'll try to release an update shortly that takes ESR into the account.

**Comment by desiregn** [comment]
Thank you

**Comment by GChristensen** [comment]
The update that should work on ESR 68 is there, please try to force addon update through the cog menu on Firefox addons page.

**Comment by desiregn** [comment]
Thanks, I noticed a change today. But changed tomorrow for non-ESR
