### ISSUE TITLE
Doesn't save the page

### ISSUE THREAD

**Issue by rubel-22** [GChristensen/scrapyard#26]
Doesn't save the page https://support.mozilla.org/ru/kb/upravlenie-tipami-fajlov

**Comment by GChristensen** [comment]
mozilla.org pages have a special status in Firefox, so addons can't access them. It seems that currently, subdomains of mozilla.org are not listed in error detection, so no error message is shown (will be shown in the future).

**Comment by rubel-22** [comment]
Still, the ScrapBook 1.5.14 extension in Mozilla Firefox 56.0 perfectly saves this page to its base.

**Comment by GChristensen** [comment]
Firefox Quantum is a quite different browser which has quite different extension model. Try to play with **extensions.webextensions.restrictedDomains** setting in **about:config**.
