### ISSUE TITLE
Lost saved pages

### ISSUE THREAD

**Issue by snoitallicso** [GChristensen/scrapyard#27]
I've lost all my pages and save new... So now I have only new. Is there a way to restore and merge it with old data to being available in sidebar?

    FF version: 81.0.2
    Extension version: 0.4.18

**Comment by GChristensen** [comment]
1. How did you lost them. Is it was Firefox refresh or addon reinstallation?
2. Open Scrapyard settings, press F12, in the developer tools open the "Console" tab, paste the following code at the bottom line and press ENTER:

```javascript
var _db = indexedDB.open("scrapyard")
_db.onsuccess = function(event) {
  var db = event.target.result;
  var rows_req = db.transaction(["nodes"]).objectStore("nodes").getAll();
  rows_req.onsuccess = function(rows_evt) {
   rows_req.result.map(r => JSON.stringify(r));
   console.log(rows_req.result.filter(r => r.type == 4).map(r => r.name + " ||| " + r.uri).join("\n"));
  }
}
```
This will show URLs and titles of all archived pages available. If you can find the old ones, they are still there.

**Comment by snoitallicso** [comment]
No any change. Just opened scrapyard without internet connection. Maybe that is not a reason.
I see only new urls :(
