### ISSUE TITLE
Looks Promising, But Can't Import RDF

### ISSUE THREAD

**Issue by BrendaEM** [GChristensen/scrapyard#3]
Hi, when I try to import my scrapbook.rdf, the following graphics is all I get.

BTW, I find that the (Windows) version has unusual / \ in the balloon help for the path.

I also tried loading 2 different scrapbooks, and even tried copying the folder to the root of the drive.

I do have a fairly large scrapbook, at 3,200 item. Perhaps that's it. The progress indicator does finish.

BTW, thanks for working on this. The loss of Scrapbook was devastating to my projects and studies. This looks like the most promising project I have seen so far.

Thank you : )

![Clipboard01](https://user-images.githubusercontent.com/20957198/68641042-74e9d400-04be-11ea-8fc3-3a7116396459.jpg)

**Comment by BrendaEM** [comment]
I was looking at the Scrapyard import. I am not a java programmer, but it appears that I have a later format NS7, which has additional NS7:chars and NS7:icon fields.

I don't know if this helps, but my RDF, starts like:

```
<?xml version="1.0"?>
<RDF:RDF xmlns:NS7="http://amb.vis.ne.jp/mozilla/scrapbook-rdf#"
         xmlns:NC="http://home.netscape.com/NC-rdf#"
         xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <RDF:Description RDF:about="urn:scrapbook:item20070228174915"
                   NS7:id="20070228174915"
                   NS7:type=""
                   NS7:title="Electrolytic Machining of Brass, Part II"
                   NS7:chars="UTF-8"
                   NS7:comment=""
                   NS7:source="http://steampunkworkshop.com/electro-mach2.shtml"
                   NS7:icon="resource://scrapbook/data/20070228174915/favicon.ico" />
  <RDF:Description RDF:about="urn:scrapbook:item20060708135619"
                   NS7:id="20060708135619"
                   NS7:type="bookmark"
                   NS7:title="Analytic Cycling, Interactive Methods for Estimating Cycling Performance Parameters. Tom Compton"
                   NS7:chars=""
                   NS7:comment=""
                   NS7:icon="http://www.analyticcycling.com/favicon.ico"
                   NS7:source="http://www.analyticcycling.com/" />
```

Thanks.

**Comment by GChristensen** [comment]
Should be fixed in v0.3.7.

**Comment by BrendaEM** [comment]
Thank you. It imports now.
I am sorry for the late reply.

[Looking at Scrapyard, I do have a bit of trouble telling if a link is a save or a bookmark. I also wish I could have a choice to fork a new window by middle clicking, or just open into the last window by clicking, when culling/sorting through my archive, I ended up just closing the browser every so often, rather than closing all the tabs.

For backing up, I am assuming that the data is saved in the extension folder?

So far Scrapyard looks like it may be the great Scrapbook replacement I and so many others have been looking for. Thank you.]

**Comment by GChristensen** [comment]
> I do have a bit of trouble telling if a link is a save or a bookmark. 
Help states that archives are marked with an italic font.

>I also wish I could have a choice to fork a new window by middle clicking, 
Middle clicking does exactly that.

>or just open into the last window by clicking
It is possible to add a such option.

>For backing up, I am assuming that the data is saved in the extension folder?
At files in downloads folder.
