### ISSUE TITLE
Archived pages make remote connections

### ISSUE THREAD

**Issue by konstruktiv** [GChristensen/scrapyard#30]
First of all, thanks for developing Scrapyard!

I noticed that when opening an archived web page, a network connection is established to the source servers. It looks like Scrapyard loads some content remotely, even though the page is archived.

Why is this and how can archived pages be stopped from making remote connections?

**Comment by GChristensen** [comment]
It may try to load scripts (in vain, since Firefox won't allow this) or some resources from CSS (it is hard to say what exactly without concrete instances). It is very hard to tackle anyway since it would require sieving everything what is possible to imagine for hanging URLs.

**Comment by konstruktiv** [comment]
There must be a way, because the original Scrapbook plugin does not load content remotely when opening an archived page.
