### ISSUE TITLE
Cyrillic encoding breaks after editing and saving a note 

### ISSUE THREAD

**Issue by rubel-22** [GChristensen/scrapyard#31]
Select and save some of the text from the page
http://forum.ru-board.com/topic.cgi?forum=5&topic=50644&start=1060#9
All OK.
![Снимок экрана (41)](https://user-images.githubusercontent.com/51868299/106932634-675ae280-6731-11eb-9cd9-320864b55fa8.png)

Then I edit this note
![Снимок экрана (42)](https://user-images.githubusercontent.com/51868299/106932665-72157780-6731-11eb-8678-c0384dd70a9f.png)

Then I save and get mackerel 
![Снимок экрана (43)](https://user-images.githubusercontent.com/51868299/106932693-7b9edf80-6731-11eb-8860-7df1e0887def.png)

**Comment by GChristensen** [comment]
Will be fixed in v0.5 soon.

**Comment by rubel-22** [comment]
Thanks a lot for the fix, it works great!
