### ISSUE TITLE
When opening scrapyard for the first time, note icons are not displayed in the sidebar.

### ISSUE THREAD

**Issue by rubel-22** [GChristensen/scrapyard#33]
When opening scrapyard for the first time, note icons are not displayed in the sidebar.
After a while, the icons appear. Aren't they stored locally?
![22](https://user-images.githubusercontent.com/51868299/107871870-f4830180-6ebe-11eb-97d7-83ac8a59c789.png)
And if there is no Internet, then the icons do not appear at all.
Is it being treated? 
![23](https://user-images.githubusercontent.com/51868299/107871875-17adb100-6ebf-11eb-8fca-e4a635b414ec.png)

**Comment by GChristensen** [comment]
>Aren't they stored locally?

Not automatically, if these are old bookmarks and "Repair icons..." context menu wasn't run on the folder in which they are stored.
Can't reproduce this, and this may depend on the capacities of your hardware. Are they displayed simultaneously or randomly?

**Comment by rubel-22** [comment]
Thank. Everything worked out when I did restore the icons in the context menu.
Displayed even when there is no internet.
Great extension! 
![ruka106](https://user-images.githubusercontent.com/51868299/107882843-fff91b80-6f04-11eb-853e-9ef73f0731fa.gif)
