### ISSUE TITLE
Lost Firefox Folders

### ISSUE THREAD

**Issue by atherworld** [GChristensen/scrapyard#34]
I clicked on my Firefox Bookmark List in the  main Scrapyard window, and now my list of Bookmark Folders are gone.  I can no longer choose where to place a bookmark. it seems my Bookmark Toolbar option has vanished. I can't get it back. It doe,s however, appear in the Sidebar if that option is selected.

**Comment by GChristensen** [comment]
Should be fixed in v0.6.1.
