### ISSUE TITLE
Full Text Search does not work on some sites

### ISSUE THREAD

**Issue by Xiomber** [GChristensen/scrapyard#42]
Full text search does not work on some archived sites. For example, on the saved sites of Envato Market https://themeforest.net and https://graphicriver.net. Content search in the sidebar also doesn't work on saved pages from these sites. It can be fixed?
Rebuild the index does not solve the search problem on these sites. In the original ScrapBook, the search on these sites works without problems.

**Comment by GChristensen** [comment]
Fixed (you need to resave the pages after the update to the new version).
