### ISSUE TITLE
Port to Chromium

### ISSUE THREAD

**Issue by smaragdus** [GChristensen/scrapyard#5]
I would like to ask- is there any chance [Scrapyard](https://gchristensen.github.io/scrapyard/) to be ported to Chromium? After using Firefox for more than a decade my patience was over and I switched to a Chromium fork. Nowadays I use Firefox only to test extensions not available for Chromium. Scrapyard is definitely one of the Firefox extensions I would like to see ported to Chromium.

Happy New Year!

**Comment by GChristensen** [comment]
Only if Chromium gets a sidebar with API, similar to Firefox, which is highly unlikely (there is currently no sidebar).
