### ISSUE TITLE
ScrapYard Sync Issue

### ISSUE THREAD

**Issue by estochin** [GChristensen/scrapyard#50]
I am getting an error in ScrapYard that says: Cannot synchronize with an empty or read only data base.
Any ideas hoe to fix this so I can sync my bookmarks?

Thanks in advance
![ScrapYard Error](https://user-images.githubusercontent.com/100220727/155167877-f885eab5-ce00-415a-86b2-85999b1b6f29.jpg)

**Comment by GChristensen** [comment]
Probably, your sync storage became empty somehow, or you created it with an empty database. This is a protective measure which prevents you to lose your content if sync storage becomes empty by some reason. You need to reinitialize it. Just delete everything in your sync folder, and unset and set again the "Enable synchronization" check at the sync settings. If you have no bookmarks in scrapyard, you will get the same error.
