### ISSUE TITLE
Easier Way To Add A Bookmark

### ISSUE THREAD

**Issue by estochin** [GChristensen/scrapyard#51]
I was hoping that if I created a new folder in my Bookmarks Menu, I could simply drag the browser tab and drop it in the new (or existing) folder and have a new bookmark. However apparently I have to use the Scrapyard Icon at the top of my browser and create a bookmark that way.

Any thoughts on dragging and dropping a tab to a folder ?

Thanks,

Jim

**Comment by GChristensen** [comment]
Unfortunately, WebExtension API does not support this functionality. An alternative is to use iShell Scrapyard commands.
