### ISSUE TITLE
Mouse wheel scrolling in toolbar icon dropdown doesn't work now

### ISSUE THREAD

**Issue by jgm2** [GChristensen/scrapyard#55]
In the list of Scrapbook folders a user has created, when saving a new scrap.  No vertical scrollbar anymore either.

**Comment by GChristensen** [comment]
Can not reproduce.
What version of Scrapyard it is? If it is 1.1, please try to update to 1.1.1 and check again.

**Comment by jgm2** [comment]
Yeah I’m on 1.1.1.  This problem just started this morning, after leaving Firefox open overnight and an auto update of the extension probably happening.  I see you’ve pushed out a couple releases in the recent past.

 

To be clear, here’s a screenshot:

 



 

Can’t mouse wheel scroll in that folder list and no vertical scrollbar either.  I’ve restarted FF several times.

**Comment by jgm2** [comment]
Windows 11 Pro, 22000.739, FF 102.0 64bit

 

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, July 3, 2022 11:52 AM
To: 'GChristensen/scrapyard' ***@***.***>; 'GChristensen/scrapyard' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [GChristensen/scrapyard] Mouse wheel scrolling in toolbar icon dropdown doesn't work now (Issue #55)

 

Yeah I’m on 1.1.1.  This problem just started this morning, after leaving Firefox open overnight and an auto update of the extension probably happening.  I see you’ve pushed out a couple releases in the recent past.

 

To be clear, here’s a screenshot:

 



 

Can’t mouse wheel scroll in that folder list and no vertical scrollbar either.  I’ve restarted FF several times.

**Comment by GChristensen** [comment]
Can not see screenshots. What is the version of Firefox?

**Comment by GChristensen** [comment]
Ah, see 102.

**Comment by GChristensen** [comment]
Should be fixed 1.1.2. Please, update.

**Comment by jgm2** [comment]
That did the trick.  Thank you.
