### ISSUE TITLE
Legacy Scrapbook RDF on MAC ....?

### ISSUE THREAD

**Issue by WebsterNYC2** [GChristensen/scrapyard#57]
Hi can you offer any Sync workaround for Mac users (you cuould at least mention in the app manual that Mac users are out of luck ...)? 

Can I take a copy of my legacy Scrapbook RDF file to a Windows machine, sync with the Windows helper application, copy the resulting Firefox file from the Windows machine (from whatever internal location it is stored), and paste it into Firefox on my Mac (to whatever internal location it is supposed to be stored in)?

If not, is there a possibility of an OSX compatible helper app? Or could it be made to work with some kind of Windows emulator like Virtualbox?

Many thanks!

**Comment by GChristensen** [comment]
You can install the helper application on Mac, although there is a lot of manual work. You need to install Python, the app package, and configure the native Firefox manifest. The details are provided in the readme file of the helper app archive.
