### ISSUE TITLE
Import/Export from Scrapbook X into Scrapyard

### ISSUE THREAD

**Issue by jweber714** [GChristensen/scrapyard#6]
Exactly how do I export/import my folders and pages from Scrapbook X into Scrapyard.  I've looked everywhere for how to do this.  I thought this would be easy to figure out, but haven't been able to.  Can you please help me?  Thanks.

**Comment by GChristensen** [comment]
If you are on Linux, you need to set up a web-server which will serve all files in your scrapbook RDF folder. Then you need to provide an HTTP link of scrapbook.rdf to the import page (see help baloon there).
If you are on Windows, just supply the full path to scrapbook.rdf as it showin in the help baloon.
