### ISSUE TITLE
Update Helper app to version 2.0 -> saved web pages inaccessible

### ISSUE THREAD

**Issue by Robby-Jo** [GChristensen/scrapyard#60]
Just updated the helper app from v 1.0 to v 2.0 under Firefox. Now when I try to access any of my saved web pages, it results in the error message "Not found". 

Updating Scrapyard from v. 2.0 to v 2.0.1 did not solve the problem.

When updating the helper app, I had closed Firefox and restarted the PC after the update.

Is there a solution in sight or should I be worried? :-)

**Comment by GChristensen** [comment]
It is necessary to transfer your content to disk. The direct link to the instruction could be found at the "About" settings tab.
The instruction is located at the "Transition" settings tab. Basically, you need to specify data path at the main setting page and click the "Transfer content" link near the field.

**Comment by Robby-Jo** [comment]
> It is necessary to transfer your content to disk. The direct link to the guide could be found at the "About" settings tab. The guide is located at the "Transition" settings tab. Basically, you need to specify data path at the main setting page and click the "Transfer content" link near the field.

Ahhh, sorry, typical manual-not-read mistake I made there. However, the instructions for the "Transition" quickly solved the problem and - a pleasant side effect - Firefox now starts much faster again by swapping out the data in the file system on disk. Thank you for the prompt support!
