### ISSUE TITLE
Bookmark button bug?

### ISSUE THREAD

**Issue by LastPirateKing** [GChristensen/scrapyard#61]
In the latest version, clicking on "Bookmark" button in the popup displays similar Helper App installation information as clicking on "Archive". I guess this is a bug? Or is the Helper App now required when saving bookmarks?

**Comment by GChristensen** [comment]
>Or is the Helper App now required when saving bookmarks?

Yes, the existing content also should be transferred to disk. The transition manual is on the "Transition" options tab.
