### ISSUE TITLE
Keeping Scrapyard Data Linked to Browser

### ISSUE THREAD

**Issue by Deagan** [GChristensen/scrapyard#62]
I was using previous versions of Scrapyard to archive pages into my Firefox Bookmarks Toolbar, but now it seems that I can't do this.

I can only archive pages into the Scrapyard "Default" folder and store them there for reference later. Whenever I archive pages into my Browser's "Bookmarks Toolbar" folder, it is erased upon browser close.

Any way to preserve archived pages, even when saved into the browser's various Bookmark Folders?

**Comment by Deagan** [comment]
I think if Scrapyard could archive the page into the Database, then sync archives into their respective folders upon browser open, that would fix the issue?

**Comment by GChristensen** [comment]
Currently there is no way. No content is saved into the browser bookmarks in 2.0, and it is not recommended. Although, Scrapyard 2.1 (coming soon) will have a mode to store all content in the browser internal storage without the need to install the helper application as v1.x did. Most likely it will be possible to save archives to browser bookmarks, but this mode will have limited capabilities. 

In the broader sense, I suppose the problem could be solved with some quick access interface similar to the bookmarks toolbar, but there is no such thing in Scrapyard now.

**Comment by GChristensen** [comment]
Unfortunately, it will be impossible to save archives to the browser bookmarks in v2.1, although it will be possible to use it without helper.
