### ISSUE TITLE
I can't export to JSON

### ISSUE THREAD

**Issue by NicolasWladyslaw** [GChristensen/scrapyard#65]
I can't export single shelves nor « everything » to JSON.

I get an error message « The native application on port 20202 is not available » then a progress bar is showing — it's fast with shelves with only a few folders and links, takes longer with bigger shelves — and I can finally save the export. However the export file is empty. Also it is sometimes an HTML file instead of JSON.

Backend installed version is v2.1. I use Brave Browser on Linux Mint 20.1 Cinnamon.

Am I doing something wrong ?

**Comment by GChristensen** [comment]
>The native application on port 20202 is not available

This means that the port is either taken by some other server, or the already running helper app from another browser or ceased instance of Firefox. There are several possible solutions:

**Comment by GChristensen** [comment]
1. Reboot the coumputer.
2. Change the port in settings to some other value.
