### ISSUE TITLE
Disk storage is missing or empty

### ISSUE THREAD

**Issue by kaba11** [GChristensen/scrapyard#66]
If I specify in settings, Content folder OneDrive/Apps/Scrapyard/Sync and refresh the app in Windows, I get an error: the disk storage is missing or empty.

**Comment by GChristensen** [comment]
Do you specify the full absolute path? OneDrive/Apps/Scrapyard/Sync is a non-existent one. It should look like:

C:/where/my/OneDrive/Apps/Scrapyard/Sync

It is possible to find out the exact path in the OneDrive Settings by clicking the "Choose Folders" button on the "Account" tab.

**Comment by kaba11** [comment]
> 

Thanks my OneDrive is problematic, so if I instead use DropBox, I input C:\Users\kaba11\Dropbox\Apps\Scrapyard\Sync - the folder I created on my desktop (with same error). So in Dropbox where do I find this absolute path?

**Comment by GChristensen** [comment]
In Dropbox it is located at the "Sync" tab in preferences (the preference option is available at the user profile dropdown menu).
Please explain the exact sequence of actions when you get this error. The path you listed above should work.

**Comment by GChristensen** [comment]
This error will indeed appear if nothing was saved to the storage, because it is indeed empty. Please try to save something.

**Comment by kaba11** [comment]
I put a url in the sync folder in Dropbox on my laptop, C:\Users\kaba11\Dropbox\Apps\Scrapyard\Sync. I searched on it from the Scrapyard right hand box in the browser, it is not found. Also I note your example link in the help section uses forward slashes, <your cloud folder>/Apps/Scrapyard/Sync. I have the same error.

**Comment by GChristensen** [comment]
If you are trying to refresh the empty storage from the sidebar panel, Scrapyard will display this error. This is the protection from the accidental deletion of the local browser internal database (although it is not fatal) if the storage folder is unplugged or not available. To fix this, just try to bookmark or archive something.
