### ISSUE TITLE
Please Help With Getting the Bookmarks From my Browser

### ISSUE THREAD

**Issue by Chuck-7** [GChristensen/scrapyard#67]
Hello, GChristensen !!

I Think that I may have done something Totally Incorrect – Because ALL of my Browser’s Native Bookmarks Seem to have Disappeared!! ...

AFTER I Installed Scrapyard in Brave, {{And Doing Quite a Lot of Archiving;  And Then penning a Totally **_Glowing_** Review of Scrapyard in the “Chrome Web Store”} — PLUS:  My Brave **_Bookmarks_** ALSO All Seemed to be FULLY Accessible—So Much So That I am now considering **Discontinuing** my use of the _Other_ Fine (Russian) Extension “Raindrop.io”.

BUT!!  Now I have a **Huge** Problem!!  I Noticed When I _{Just About 90 Minutes Ago Now}_ Was Working in Brave’s Own Bookmark “Manager” (^+O), I Noticed That I had a few Redundant Folders, Etc., SO I Cleaned Out ALL of my OLD & No-Longer-Used Bookmark Folders, AND Moved ALL Folders (With Their Bookmarks) into the MAIN Folder {Which is Titled::  ""Bookmarks""} SOOO, there are Now Far Fewer Bookmarks & Everything is ALL Nice & Organized – – –

But **_THEN_** it Seemed that TRAGEDY Had Struck !!! —>
When I Then _{After Organizing}_ Returned To My {{ New & Now My FAVORITE }} Bookmark Interface::  **Scrapyard** —>>
   And I Selected SHELF “Browser” — And Went to MAIN FOLDER “Bookmarks”—>>Now There Exists ONLY the Top-Level Folders—Each of Them PREFIXED With the GLOBE ICON — And EVERY ONE of them — **EMPTY** ! ! ! ! !

I Can Only HOPE That You Can Help Me to Figure Out HOW I Can Cause Scrapyard To — ONCE AGAIN — Communicate With Brave’s Native Bookmark Feature!!!

Thank You VERY Much for Helping this Forlorn & Wayward Pilgrim!!

**Chuck-7**
{Now Better Known as “LSeek”}

**Comment by GChristensen** [comment]
Hi,

Please, go to scrapyard settings and uncheck "Enable browser bookmarks integration" at the Browser Bookmark section on the main "Settings" tab. Wait ~10-20 sec and check it again.

I'll test more on Brave with the native bookmarks.

**Comment by Chuck-7** [comment]
Hello Again, GChristensen !!
YES!!
That Seems to Have Brought my Bookmarks __ **BACK** __!!!  {PHWEWWW!!—That was a Relief!!}

So Now::  2 Questions, Please::

1.  Do You Believe that it will be Necessary to Uncheck that Integration Setting **OCCASIONALLY** To FORCE That Same FULL Synchronization??   And . . .

2.  Since I have now experienced the Excellence of Scrapyard, it Personally Appears to me that it Completely Supersedes Raindrop.
     In YOUR Personal Opinion, do you believe there is ANY Reason for me to Retain Raindrop?? — Can I Not Now Simply Rely Totally Upon Scrapyard?

Thank You Again,
LSeek

**Comment by GChristensen** [comment]
1. Because some weird synchronization is required to access native browser bookmarks, it may occasionally happen when heavy operations on the native bookmarks are preformed. Although this may change if the cause of this bug is easily determinable.
2. Practice is the criterion of truth. I wouldn't delete anything from other services I have when transitioning to something new. I use Scrapyard pretty much myself, but the only browser where it works decently is Firefox.

**Comment by Chuck-7** [comment]
GChristensen::
I Used to Prefer Firefox Too, But the “Management” of Firefox seems to OFTEN Lack Scruples & have infuriated me far TOO Often. 

But More Importantly, There are FAAAAAAARRR More Extensions for Chrome than there are within Firefox. 

I Think that a Key Reason that Firefox seems to work better for Scrapyard _Presently_ is because it is simply a FAR more Mature Product!::  Who Knows?—After another Seven months, Scrapyard may work every bit as good within Chrome As it does now in Firefox.  Anyways, it is totally Not an inconvenience for me to occasionally run that “Disconnect” that you showed me. 
Plus To Me, Scrapyard is **_FAR_** MORE Powerful than Raindrop—Explicitly Because its Archival works One Hundred Percent of the Time::  Raindrop’s ““Permanent Saves”” (So-Called) Only work Ninety-Four Percent of the Time—Which is Simply UNacceptable!!!

Thank You Again, GChristensen, Both For Your Assistance And Your Comments::  I will Keep Raindrop for about Four More Months, but attempt to rely Wholly upon Scrapyard.

– LSeek
