### ISSUE TITLE
Archived pages might get lost when moving to cloud shelf

### ISSUE THREAD

**Issue by dnabb** [GChristensen/scrapyard#69]
Steps to (hopefully) reproduce:

- Archive a larger number of pages (say, 20 to 30) into the default shelf and close them
- Create a new folder as a subfolder of the cloud shelf (in my case synced with Dropbox, not sure if the problem is present with other cloud providers)
- Move the archived pages from the the default shelf to the newly created folder on the cloud shelf
- Open the recently moved archived pages

The recently moved pages take a while to load on reopening (probably because Scrapyard is still syncing with the cloud).

At some point, something seems to go wrong, and some of the archived pages start returning "not found".
After a few seconds, Scrapyard seems to triggers a reload. 
After the reload, some (or in some cases, all) the pages that were involved in the moving either disappear from the shelf or are still present on the shelf but return "not found" when trying to open them.

From Dropbox side, some of the pages that were being moved seems to lack one or more of the necessary files (as example, might have `archive_index.json`, `icon.json`, `item.json` but no .blob file), which makes them unusable.

**Comment by GChristensen** [comment]
Will be fixed in v2.1.9.
