### ISSUE TITLE
Scrapyard data files location?

### ISSUE THREAD

**Issue by jweber714** [GChristensen/scrapyard#7]
I finally have my Scrapyard up and running.  I see in BrendaEM's comment she was asking where data files were located for backup purposes.  I believe you responded they were located in the Downloads folder (Windows 10?).  I checked there on my PC and no such luck.  I, too, would like to know where they are located for the same reason.  On my old PC, the Scrapbook folders were easy to find in my Profile in a folder named Scrapbook; and I even created some additional scrapbooks and placed them in my Documents folder.   I have looked pretty much everywhere and can't find anything recognizable.  Where is the default location of the data files, and how can I identify them?  

In an unrelated matter; I was originally trying to import the RDF files from my old PC via SD card, and it wasn't working; I got the folder tree, but no actual data.  I finally figured out I had to copy the parent folder containing the RDF plus all the subfolders with it.  Then importing the RDF worked just fine.  One strange thing; when I imported from the SD card it worked fine, but if I copied the folders to my desktop on the target PC, then tried to import, Scrapyard stated it couldn't find the RDF file.  Strange.  

In any case, Scrapyard is a great app, once set up correctly!  Wish there were more comprehensive instructions.

**Comment by GChristensen** [comment]
Scrapyard stores everything in browser local storage, so there is no way to access it directly. You can back up any shelf (or everything) through the shelf operation menu into a JSON or ORG file. By default, backup files are saved in the system Downloads folder.
