### ISSUE TITLE
Incorrect saving of fonts

### ISSUE THREAD

**Issue by Xiomber** [GChristensen/scrapyard#70]
Hello. Fonts are displayed incorrectly on saved pages. This does not appear everywhere, but only on some sites, for example, themeforest.net. This is clearly a Scrapyard problem because the ScrapBook and ScrapBee extensions save the fonts correctly, they are the same there as on the original page.
This is how fonts are displayed on the original page (and when archived in ScrapBook and ScrapBee):
https://s1.hostingkartinok.com/uploads/images/2023/03/af5983875ed51813afdd0ff17420197f.png
This is how fonts are displayed in the archived Scrapyard page:
https://s1.hostingkartinok.com/uploads/images/2023/03/f1fab559958a6beda010a1766f091fac.png

It started after one of some Scrapyard updates before that the fonts on the archived pages were saved correctly. This problem with the font is both in Scrapyard for Firefox and for Chrome.

The original page from which the screenshots were taken:
https://themeforest.net/item/razzi-woocommerce-wordpress-theme/31833761

**Comment by GChristensen** [comment]
Yes, I can reproduce this. It seems this happens because Scrapyard adds

**Comment by GChristensen** [comment]
the following style to each page:
body {
  font-family: initial;
  font-size: initial;
}
This is necessary to overcome style changes on Chrome for the IDB version of storage. When using this style on Chrome, the fonts will also be different and significantly smaller.
I'll thing what to do with this. Probably, an additional option in settings should be added to enable this mode manually.
