### ISSUE TITLE
[Issue] Scrapyard native application v2.0+ is required. 

### ISSUE THREAD

**Issue by Terkyz** [GChristensen/scrapyard#73]
After installing several dependencies and doing the `./install sh` the installation did not proceed, so I had to do `sh install.sh` and I don't know it was installed this time, but Firefox does not recognize the backend... 

I'm in KDE Neon, with the default browser, which is Firefox (as a binary, not as Flatpak or Snap) and even if I reinstall the extension, or restart the browser nothing changes.

[Here's](https://i.imgur.com/Zy4Irmt.png) the problem with some logs. And [here](https://i.imgur.com/fwvvuHZ.png) the same with `./install.sh`

**Comment by GChristensen** [comment]
Judging from the logs, you need to add /home/tryz/.local/bin to PATH. Somewhere in /etc/environment probably.

**Comment by GChristensen** [comment]
It is also worth to check which profile is used by the Firefox you use. Its path could be found at the about:support page. Scrapyard backend installer writes the native manifest into ~/.mozilla/native-messaging-hosts/scrapyard_helper.json. If the profile is somewhere outside of ~/.mozilla , this may explain why the backed is not detected.

**Comment by Terkyz** [comment]
Honestly I don't know what to do, the Firefox profile is in /home/tryz/.mozilla/firefox/r4w3ppcj.default-release, after checking that, I added to PATH the directory /home/tryz/.local/bin and still Scrapyard says that I don't have the backend installed.

I tried to reinstall the scrapyard backend, and remove the two dependencies that before gave PATH error (Flask and Scrapyard Backend) and in fact this time the reinstallation did not give me any error, but it still does not detect the backend.

I checked also the scrapyard_backend,json and the path to the host points to /home/tryz/.local/bin

Most probably it's my mistake, although it's not the first time I have an error like this with the Firefox version of KDE Neon.

**Comment by Terkyz** [comment]
It is, without a doubt, a problem with the version of Firefox that KDE Neon comes with. I downloaded the Firefox binary from the official Firefox site, and what a surprise: Scrapyard works [perfectly](https://i.imgur.com/iQJNrn1.png) and automatically detects the backend.

Is KDE Neon using Firefox as snap or flatpak? As much as I researched I never came to a concrete answer but that's the only thing I can think of.

**Comment by Terkyz** [comment]
In fact, after bothering you I have a question, what functionalities do I lose if I use Scrapyard without the backend?

**Comment by GChristensen** [comment]
1. [There is](https://wiki.mozilla.org/WebExtensions/Native_Messaging) also the global manifest directory: /usr/{lib,lib64,share}/mozilla/native-messaging-hosts/ . But writing there may require root access.
2. Without the backend it is not possible to import RDF in some modes (quick import that only imports directory tree), it is not possible to use built-in backup/restore, upload local files as archives and transition to the file-system-based storage. There are additional limitations on Chrome, related to styling of archived pages and the archive toolbar. It is recommended to backup the entire Firefox profile if you do not use backend.
