### ISSUE TITLE
Sync between devices with Firefox Sync?

### ISSUE THREAD

**Issue by silverhook** [GChristensen/scrapyard#75]
It’s not clear from the documentation (or I did not find it) if by using the browser’s database Scrapyard data is synced between different Firefox devices/Profiles using Firefox Sync.

If it is, that would be great to know, so one can avoid syncing through an additional cloud provider.

If it is not, I would like to request it – if it is technically feasible, of course.

**Comment by GChristensen** [comment]
No. Firefox Sync capacity is only 1MB, it is not possible.

**Comment by silverhook** [comment]
That makes sense then. If you haven’t yet, that would be good to clarify in the documentation/FAQ.
