### ISSUE TITLE
Not Saving Websites To Scrapyard Bookmarks

### ISSUE THREAD

**Issue by xfound** [GChristensen/scrapyard#76]
It is not working. I installed what they asked but websites are not being saved to Scrapyard

I can make folders in Scrapyard but cannot save websites to scrapyard.

Help please

(772) 324-7478‬ 
Scott

**Comment by GChristensen** [comment]
Hi,

It's impossible to say anything without some debug context. Does it shows any error messages. If the backend application is used, does URL http://localhost:20202/ open in the browser?

**Comment by GChristensen** [comment]
If there are no messages and the URL opens, you need to paste the following link into the url bar 

about:devtools-toolbox?id=scrapyard-we@firefox&type=extension

And post here the content of the Console tab.

**Comment by xfound** [comment]
![Screenshot 2023-05-18 155954](https://github.com/GChristensen/scrapyard/assets/133817463/6d6ff37e-de91-4a0f-8925-3412745833c7)

**Comment by xfound** [comment]
Also, I am getting this message when i start firefox
![Screenshot 2023-05-18 160326](https://github.com/GChristensen/scrapyard/assets/133817463/a85e20e5-d713-4532-974b-05c60934bcea)

**Comment by xfound** [comment]
Bookmarks seem to be saving to cloud.

**Comment by GChristensen** [comment]
Your settings should look something like this:
![settings](https://github.com/GChristensen/scrapyard/assets/170405/e9f82f11-a667-4cf7-83c3-57b73ca134e9)
