### ISSUE TITLE
some feature suggestions

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [GChristensen/scrapyard#78]
I tried to use this extension but...

- could not undo document edits and dom erasures
- would like to pick a dom element to be the only visible one instead of having to erase everything around it
- right click a text selection to mark it would be easier
- archiving a page in the sidebar with right click makes the link no longer work

**Comment by GChristensen** [comment]
>I tried to use this extension but...
>could not undo document edits and dom erasures

This will require an implementation of a virtual DOM and rendering the archived page through it. A task of a scale of a transnational megacorporation. Scrapyard is developed in my free time, which is scarce, and almost nobody donates...

>would like to pick a dom element to be the only visible one instead of having to erase everything around it
>right click a text selection to mark it would be easier

Selection saving works this way. This is mentioned in the user manual. You need to select a fragment of a page and then press "Archive". Additional option that duplicates this functionality in the editor will clutter the interface.

>Archiving a page in the sidebar with right click makes the link no longer work

Yes, the bookmark is replaced with the archive. Use "Open original URL" to open the original document.
