### ISSUE TITLE
OneDrive - Storage not working

### ISSUE THREAD

**Issue by CisIsNotDb** [GChristensen/scrapyard#79]
Hi. At first - great app.
I am having problems with the "Content Folder" in Settings. I gave access/sign in to OneDrive, but it is not working. I used the debug feature in Firefox for the AddOn and it showed an error. I have 2FA on OneDrive. Do I need an app password for Scrapyard?

![Screen-2023-06-08_08-35-37](https://github.com/GChristensen/scrapyard/assets/48147729/647ff161-2793-4e64-a18a-d3e21fdb6744)

![Screen-2023-06-08_09-17-28](https://github.com/GChristensen/scrapyard/assets/48147729/ffe6587b-cadf-45f3-bc8c-15444cd0a840)

![2023-06-08](https://github.com/GChristensen/scrapyard/assets/48147729/e6b64e1b-8f3e-44f8-a577-01f65aa69177)

**Comment by GChristensen** [comment]
Hi,

It is necessary to expand the content of the error by clicking at the triangles at right (they may be nested). Without this it is hard to say what is happening.

**Comment by CisIsNotDb** [comment]
I can make a file and send this to you via email. Is this ok for you? I don't want (possible) critical data in the wild. Thank you.

**Comment by GChristensen** [comment]
It is possible to copy the content of the error as text.

**Comment by GChristensen** [comment]
Actually there is no bug. It is necessary to make a bookmark, and then it will work. It's an edge case that probably needs better documentation or error handling.
