### ISSUE TITLE
Links being replaced with separators when separators are present?

### ISSUE THREAD

**Issue by MasterChiefmas** [GChristensen/scrapyard#8]
I noticed a problem that I haven't exactly figured out what's happening. I use separators in my bookmarks to sub-group bookmarks together. At first, I thought that on restart, separators were sometimes being duplicated. However, I noticed recently that one of my folders seems to be missing a lot of links and has a lot more separators. 

I suspect that separators are incorrectly replacing links for some reason. I have to verify that is when it happens, I only really became suspicious when it became super obvious because I saw a folder that once had a bunch of links with some separators, to having 3 links and a lot of separators. This only seems to happen if separators were present in the folder to begin with.

**Comment by GChristensen** [comment]
It is hard to imagine how this may happen technically by itself, but the same effect could be achieved if the bookmarks were deleted from another shelf, for example, TODO, or Firefox UI.
