### ISSUE TITLE
Installing backend as admin won't work for active user

### ISSUE THREAD

**Issue by theelectricsoul** [GChristensen/scrapyard#80]
Hello

Thank you for Scrapyard :) 

**Scenario**
I am User A and need the backend installed. I can only install software as user B. So I start the installation and am being asked for admin credentials. I type in the credentials of user B and finish the installation.

**Problem**
After the installation user A still has no access to the backend. Firefox ist prompting an error. I tried restarting FF. 

![image](https://github.com/GChristensen/scrapyard/assets/10260832/c8a79b4e-ce93-4021-a746-27425f6eb2f1)

**Comment by theelectricsoul** [comment]
![image](https://github.com/GChristensen/scrapyard/assets/10260832/4b817b74-7c32-4a5f-889d-5a801d26b02d)

**Comment by GChristensen** [comment]
Hi, Firefox can only know about the backend through the Windows registry, and the installer has written everything into the registry of user B.

You may try to import a .reg file with the following content:

Windows Registry Editor Version 5.00

```
[HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\scrapyard_helper]
@="...path to manifest.json in the backend installation folder, the use of \\ as path separators is mandatory ..."
```

**Comment by theelectricsoul** [comment]
I can manage...  however... most won't :) Other would need to contact the IT department.

Additionally the user needs to have elevated user rights for installtion. This plugin might be a no go for companies, because of security concerns. Maybe there is a way to simply install the executeables into the users profile without the need for higher permissions.


Thank you for your work.
