### ISSUE TITLE
Scrapyard Sorting By name Issue

### ISSUE THREAD

**Issue by estochin** [GChristensen/scrapyard#81]
When I click on Scrapyard Sorting By Name I get an error:

Scrapyard native application V2.0+ is required.

I'm not sure what this means?

Thanks in advance for any help.

**Comment by GChristensen** [comment]
Hi,

Do you store your content in the browser internal storage? I tried sorting in this mode, it works without erros. If not, you need to install the backend application that will allow Scrapyard to write to disk (this is not possible with plain WebExtensions). The installer links are on the "Backend" tab at the add-on settings.

**Comment by estochin** [comment]
Thanks for your quick reply. I'm not sure where the content is stored - 
I simply use Firefox along with the Scrapyard extension. I used to be 
able to sort by name but now the error comes up. I wonder what I am 
missing?

Jim


--------- You Wrote ---------
From: "GChristensen" ***@***.***>
To: "GChristensen/scrapyard" ***@***.***>
Cc: "estochin" ***@***.***>; "Author" 
***@***.***>
Sent: 6/28/2023 9:40:20 AM
Subject: Re: [GChristensen/scrapyard] Scrapyard Sorting By name Issue 
(Issue #81)

**Comment by GChristensen** [comment]
This is how settings look like if bookmarks are stored in the filesystem. This option is new and it was added some time ago and it requires explicit transition which also could be cancelled.
![sy_fs](https://github.com/GChristensen/scrapyard/assets/170405/2e26062b-1254-4c89-bdac-9c662c2facce)

There is another option, to store them in the browser internal storage.
![sy_opts](https://github.com/GChristensen/scrapyard/assets/170405/4512d8b3-7b4f-4729-978b-97b416729182)

Please check, if you can open archived pages (simple bookmarks will open in either case). You may need to perform or cancel the transition to filesystem, if you haven't already.
If you can open archives, post the resulting link to determine where they are stored. If in the filesystem, this is a bug and debugging is necessary.

**Comment by estochin** [comment]
Thanks for that - I installed scrapyard-backend-2.1.2_x86_64.exe and all 
is well - sorting without any errors.

Great extension!

Jim


--------- You Wrote ---------
From: "GChristensen" ***@***.***>
To: "GChristensen/scrapyard" ***@***.***>
Cc: "estochin" ***@***.***>; "Author" 
***@***.***>
Sent: 6/28/2023 10:08:19 AM
Subject: Re: [GChristensen/scrapyard] Scrapyard Sorting By name Issue 
(Issue #81)

**Comment by estochin** [comment]
Hi,

I'm having trouble installing the current backend v2.1.2

I get this error:


Any help would be appreciated,

Jim


--------- You Wrote ---------
From: "GChristensen" ***@***.***>
To: "GChristensen/scrapyard" ***@***.***>
Cc: "estochin" ***@***.***>; "Author" 
***@***.***>
Sent: 6/28/2023 11:01:30 AM
Subject: Re: [GChristensen/scrapyard] Scrapyard Sorting By name Issue 
(Issue #81)

**Comment by GChristensen** [comment]
Hi, probably error is lost somewhere. Can you post it again?

**Comment by estochin** [comment]
Hi,

I'm having trouble installing the current backend v2.1.2

I get this error:
![Backend Install Error](https://github.com/GChristensen/scrapyard/assets/100220727/01efd78d-ba74-41a2-9571-0c10b968c5af)

Any help would be appreciated,

Jim

**Comment by GChristensen** [comment]
Probably the browser is running during the installation, and the backend is loaded.
It is necessary to close the browser before the installation of the backend. If this would not help, it is worth to try to reboot to unload all possible zombie processes.

**Comment by estochin** [comment]
Thanks - that worked.

I'm getting ready to switch from Firefox to Chrome and I will have a few questions as I go.

1st - I want to back up my current bookmarks using the Backup tool - I've used it before so I'm OK there.
My question is which set is the best to back up and do I need all these sets?
![Different Bookmarks](https://github.com/GChristensen/scrapyard/assets/100220727/62f34601-b636-4264-8787-c120bf7f91a8)

**Comment by GChristensen** [comment]
The backup tool is only for restoring already created backups. If the data is stored on the drive and not in the browser local storage, the best way to backup is just archive or backup the add-on data folder with 3-rd party backup software. If you migrating from Firefox to Chrome, just specify the path to the same folder in Chrome.

**Comment by estochin** [comment]
Thank you.

And for my Settings, Content... do I want Filesystem or Browser Internal Storage?

**Comment by GChristensen** [comment]
Filesystem is recommended for the most cases.

**Comment by estochin** [comment]
Thanks .. helpful.

More chrome questions to follow as I get deeper in.

**Comment by estochin** [comment]
So in Firefox, Scrapyard welded in a sidebar with all my bookmarks on the left which was nice:

![Firefox Sidebar](https://github.com/GChristensen/scrapyard/assets/100220727/11b50434-41f4-4f39-81c3-27c2dfd5c1a5)

However in Chrome, there is no automatic sidebar,  when I click on the Scrapyard Extension Icon, I get one pop up window on the right and when I select Sidebar from that pop up I get a floating Scrapyard sidebar. How do I have only the Scrapyard sidebar appear and have it welded into Chrome like it was in Firefox?

![Chrome Sidbars](https://github.com/GChristensen/scrapyard/assets/100220727/6d900bdd-a180-470d-82ff-4e19701e5ae6)

**Comment by GChristensen** [comment]
This is impossible, since among all browser only Firefox have sidebar that is able to host add-ons. I'd recommend to stick with Firefox.

**Comment by estochin** [comment]
Thanks for that, I'll play around and see what I can come up with 
Chrome's native sidebar.


--------- You Wrote ---------
From: "GChristensen" ***@***.***>
To: "GChristensen/scrapyard" ***@***.***>
Cc: "estochin" ***@***.***>; "Author" 
***@***.***>
Sent: 1/11/2024 11:28:36 PM
Subject: Re: [GChristensen/scrapyard] Scrapyard Sorting By name Issue 
(Issue #81)

**Comment by estochin** [comment]
Quick question... How do I get a HTML version of my Scrapyard bookmarks .. I'm fooling around with Chrome's native sidebar and it wants a HDMI file for importing

**Comment by GChristensen** [comment]
It wants bookmarks in Netscape HTML format, which is common format for browser bookmarks that contain only URLs. Since Scrapyard is an archiving  application, it can only export in its own JSON-based format. If you need to transfer URLs to browser bookmarks, you may copy/paste bookmarks from any Scrapyard shelf to the "browser" shelf in Scraypard UI.

**Comment by estochin** [comment]
Interesting .. I'm not sure I follow copy/paste bookmarks from any Scrapyard shelf to the "browser" shelf in Scraypard UI. Is there a tutorial someplace?

**Comment by GChristensen** [comment]
I've noticed above that you have only the "default" meaningful shelf. You need to select all bookmarks in it using click+Shift or click+Ctrl, copy them using context menu, switch to the browser shelf, click on its root icon and paste using context menu.

**Comment by estochin** [comment]
So I think I can follow that but how does that get me a HTML file for Chrome - I must be missing something?

**Comment by GChristensen** [comment]
You don't need a HTML file to transfer URLs to Chrome bookmarks.

**Comment by estochin** [comment]
I guess I'm still confused - when I go to Chrome, Import, it wants me to 
point to a HTML file.
Sorry, you seem to know more about this that I do but how would I get 
around pointing to a HTML file?


--------- You Wrote ---------
From: "GChristensen" ***@***.***>
To: "GChristensen/scrapyard" ***@***.***>
Cc: "estochin" ***@***.***>; "Author" 
***@***.***>
Sent: 1/12/2024 10:38:20 PM
Subject: Re: [GChristensen/scrapyard] Scrapyard Sorting By name Issue 
(Issue #81)

**Comment by GChristensen** [comment]
You just need to copy and paste bookmarks between the default and browser shelves inside Scrpayard. After that URLs will magically appear in the browser bookmarks. You do not need to import anything into Chrome using HTML. But if you archived anyting, the content will not appear in the Chrome bookmarks, because it can contain only URLs. Scrapyard was created primarily for archiving and categorizing your bookmarks on thematic shelves of which you can create as many as you wish.
