### ISSUE TITLE
Can't find stored archives.

### ISSUE THREAD

**Issue by iomari** [GChristensen/scrapyard#82]
Greeetings,
I just installed this nice extension and I have archived a few test pages.
Now how do I get to see my archived pages? I don't see where to access them.
 
OS: Linux Ubuntu 23.04
Browser: Vivaldi 6.1.3035.302 (Stable channel) stable (64-bit)

I would appreciate any help.

**Comment by GChristensen** [comment]
They are in sidebar. It could be opened with the Alt+Y keyboard shortcut or through the corresponding button at the top-right corner in the add-on popup.

**Comment by iomari** [comment]
thank you
