### ISSUE TITLE
Move Folder

### ISSUE THREAD

**Issue by iomari** [GChristensen/scrapyard#83]
Greetings,
How can I move a page to another folder?

**Comment by GChristensen** [comment]
Hi,

**Comment by GChristensen** [comment]
It is possible to move it by drag&drop, through cut/paste commands from context menu or with move-at ishell command.

**Comment by iomari** [comment]
Thank you for your quick response.

**Comment by iomari** [comment]
Greetings,
me again,
I just saved a page using Scrapyard but the links in the page are not
local. Is there a setting I'm missing?

**Comment by GChristensen** [comment]
Because only one page is saved, Scrapyard does not know about other possible pages, so it is impossible to make local links in this case. If you need to save a bunch of pages with links between them, use the site save mode. Please see the user manual for details.

**Comment by iomari** [comment]
Understood. Thanks
