### ISSUE TITLE
Cannot upgrade backend to v2.1.2

### ISSUE THREAD

**Issue by jgm2** [GChristensen/scrapyard#84]
I'm stuck here:
![image](https://github.com/GChristensen/scrapyard/assets/4467789/06786815-3eb0-435a-ae32-3ad309c0ce5d)

I'm on Windows 11 latest, have tried both the Windows and Python 2.1.2 installers, both of which appear to complete successfully.  Firefox processes are completely shut down during the upgrade attempt.  I have always been able to update the backend in the past.  Advice?

**Comment by GChristensen** [comment]
How does the error manifests itself?

**Comment by jgm2** [comment]
The upgrade just never gets recognized by the options gui in firefox, as in the screenshot I attached.  Always shows previous version.

**Comment by GChristensen** [comment]
It seems that version number inside the add-on wasn't updated, but the version number in the file name has changed. The installed version is actually 2.1.2. I'll fix this soon. 'Thanks for the report.

**Comment by jgm2** [comment]
Ah, thank you.
