### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by iomari** [GChristensen/scrapyard#87]
Greetings,
I just installed the cli backend. No issues during install but now scrapyard stopped working, I see all  my entries in the scrapyard page but clicking an any entry does nothing. Additionally, when I try to capture a page, I click on archive and nothing happens.

What has gone wrong?

Can I uninstall the backend? Or is it some other issue causing this.

thanks in advance
iomari

I just noticed that the settings page says the backend app is missing. Yet I installed it. Though because of the new version of ubuntu, pip is no longer used so I had to alter the installer.py to use pipx instead. However it ran with no error and did the installation. Is that the problem? If so, How can I undo the installer.py

I commented out line 61 and changed it as seen below:
```

# subprocess.check_call([sys.executable, "-m", "pip", "install", package_path, "--user"]) 
subprocess.check_call(["pipx", "install", package_path])

```

**Comment by iomari** [comment]
I just deleted my whole vivaldi folder and restored it from 2 days ago when scrapyard was  working, and I also did the same for my home scrapyard folder and I still can't access my pages.
Where else do I have to delete and replace? I have complete backups of my entire home folder from 2 days ago.

**Comment by GChristensen** [comment]
Hi, I've read your comment at the chrome store. Probably, there some misunderstanding, sicne I wrote my last comment before I've read your last commend. You have not lost anything. The simplest way to get Scrapyard working is to [install pip manually](https://pip.pypa.io/en/stable/installation/). Currently I have little time to work on Scrapyard, an I do this absolutely voluntarily (almost no one donates). And the support of Linux is a non-trivial headache. So, the only thing I can suggest at this time is to install pip manually. It is necessary to test if it works properly after installation through the -m pip parameter.
