### ISSUE TITLE
Threads dying during large Scrapbok rdf import

### ISSUE THREAD

**Issue by jgm2** [GChristensen/scrapyard#9]
I have a large Scrapbook rdf created over years of use, currently about 40MB and indexing probably at least 100,000 scraps inside many Scrapbook subfolders.  When I use Scrapyard to import it, setting at 8 threads, it starts off strong but after time the import slows down because each thread gradually stops working, which can be seen by the activity of the temporary tabs that the threads repeatedly create and destroy.  When a thread dies, a tab remains in, I assume, mid-import, leaving only the round hard disk graphic in the middle of the page, whose address is something like blob:moz-extension://81fc09a0-4b51-4159-8989-554870c88fef/87522985-5be6-435d-876e-5dc5f5b9b868

Eventually all of the threads die and the import completely stops.  I was only able to get about 20% through the import.

I would like to get my scraps imported into your excellent extension and finally get off of the ancient, broken-down Firefox version I need to keep using to have access to my scraps.  Is there any way I can help you troubleshoot?

Also, what is the purpose of the Quick Import checkbox during import?  The hover description doesn't make it clear to me.  I had that unchecked during the import attempt.

Thank you.

**Comment by GChristensen** [comment]
Probably, Firefox memory garbage collector can't handle 100,000 items, so it should be a Firefox problem which is hart to overcome from the extension. The quick import leaves all the files on disk, so only the tree structure is imported (but pages will open slightly slower than the ones, imported into local storage). It will not make high load on memory, so this option may work (but you will need to keep all files on disk).

**Comment by jgm2** [comment]
If the quick import works, can I continue to save scraps to that shelf in normal daily usage of Firefox (actually Waterfox in my case), where creating new scraps *will* be saved to disk?  In other words, does Scrapyard handle a shelf with mixed local storage/not local storage scraps?  Or would I have to create a new shelf to accept new scraps?

**Comment by GChristensen** [comment]
> If the quick import works, can I continue to save scraps to that shelf in normal daily usage of Firefox

Unfortunately, no. You need to create a new shelf which will store items in local storage.

**Comment by jgm2** [comment]
Ok, if that's what I have to do I'll live with it.  But I'm adding this as an enhancement request, if you want to un-close this issue:  create an option to "import directory structure only", to enable the situation where a user wants to import a large, complex Scrapbook directory structure which is hard to recreate and to continue adding Scrapyard scraps to it - it's understood that Scrapbook scraps don't get imported.  There can be a lot of value in preserving the directory structure itself.  Thanks.
