### ISSUE TITLE
Scrapyard backend auto installation fails on Windows 10

### ISSUE THREAD

**Issue by touwys** [GChristensen/scrapyard#91]
Scrapyard back-end auto installation was aborted due to error opening some "*.pyd" files for writing. Please view the following screenshots of the process: 

Firefox v131.0.3 (64-bit)
Windows 10 Pro, Build 19045.5011

•••
![20241023_130711 — Screenshot](https://github.com/user-attachments/assets/6eaa29ed-7469-4c18-9c0f-d070d18c811e)
•
![20241023_130832 — Screenshot](https://github.com/user-attachments/assets/dc2d094a-18b6-4762-a01d-2627e18fd609)
•
![20241023_130853 — Screenshot](https://github.com/user-attachments/assets/5c7bd307-32e8-4c38-ab5b-a8712d6230b6)
•
![20241023_130916 — Screenshot](https://github.com/user-attachments/assets/083267f7-e7c2-4a5f-8856-374c4f7daa58)
•
![20241023_130938 — Screenshot](https://github.com/user-attachments/assets/b922eefe-919b-4d54-93f8-c47755d6decb)
•
![20241023_131002 — Screenshot](https://github.com/user-attachments/assets/6a040c00-187e-4da7-8df9-0764216d9178)
•••

**Comment by GChristensen** [comment]
Hi, 

It is necessary to exit all instances of Firefox when installing the backend. Please reboot if this does not help, since some background Firefox instances may hang in memory.

**Comment by touwys** [comment]
> Hi,
> 
> It is necessary to exit all instances of Firefox when installing the backend. Please reboot if this does not help, since some background Firefox instances may hang in memory.

Thank you, it installed perfectly.
